# Generated by Django 4.2.2 on 2023-07-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
