# Generated by Django 4.2.3 on 2023-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="heading",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
