# Generated by Django 4.2.3 on 2023-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_post_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
